main/urls.py
from django.urls import path,include
from .views import CustomerListView, CustomerView, CustomerViewSet
from rest_framework import routers


router = routers.DefaultRouter()
router.register(r'customers', CustomerViewSet)

urlpatterns = [
    path('', CustomerListView.as_view(), name='home'),
    path('home', CustomerListView.as_view()),
    path('create-customer', CustomerView.as_view(), name='create_customer'),
    path("customer/<int:id>/update", CustomerView.as_view(), name="updat_customer"),
    path('', include(router.urls)),
    path('api-auth/', include('rest_framework.urls')),

]

pyCrudSample/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('', include('accounts.urls')),
    path('', include('django.contrib.auth.urls')),
]

main/models.py
from django.db import models
from django.contrib.auth.models import User
from .dto import CustomerDTO

class Customer(models.Model):
    class CustomerGrade(models.TextChoices):
        UNITEDSTATES = 'US','United States'
        FRANCE = 'FR','France'
        DENMARK = 'DE','Denmark'
        
    creator = models.ForeignKey(User, on_delete=models.CASCADE)
    grade = models.CharField(max_length=2,choices=CustomerGrade.choices, null=True)
    email = models.EmailField(unique=True, blank=False, null=False)
    first_name = models.CharField(max_length=200)
    last_name = models.CharField(max_length=200)
    nationality = models.CharField(max_length=200, null=True)
    birthday = models.DateTimeField()
    is_deleted = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    deleted_at = models.DateTimeField(auto_now=True)

    def to_dto(self):
        return CustomerDTO(self.id, self.email, self.first_name, self.last_name,
                           self.nationality, self.birthday, self.creator, self.grade)
    def get_choice(all_choices,search):
            for choice in all_choices:
                print(choice[0])
                if choice[0] == search:
                    return choice[1]
            return None 
    
    def getGradeKey(self, value):
        choices = dict((v,k) for k,v in self.CustomerGrade.choices)
        if value not in choices:
            return value
        return choices.get(value) 

                           

main/forms.py
from django import forms
from .models import Customer


class CustomerForm(forms.ModelForm):

    class Meta:
        model = Customer
        fields = ["first_name", "last_name", "email",
                  "birthday", "nationality", "grade"]
        widgets = {'birthday': forms.DateInput(attrs={'type':'date'})}
        
    def __init__(self, *args, **kwargs):
        super(CustomerForm, self).__init__(*args, **kwargs)
        self.fields['nationality'].required = False

main/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.generic import FormView
from django_tables2 import SingleTableView, LazyPaginator
from django.utils.decorators import method_decorator
from django.contrib.auth.decorators import login_required
from django_filters.rest_framework import DjangoFilterBackend
from rest_framework import viewsets
from rest_framework import permissions
from .serializers import CustomerSerializer
from .tables import CustomerTable
from .models import Customer
from .customerService import CustomerService
from .forms import CustomerForm



class CustomerView(FormView):
    model = Customer
    customerService = CustomerService()
    template_name = 'main/customer_form.html'
    form_class = CustomerForm
    
    @method_decorator(login_required)
    def get(self, request,id=None):
        form = self.form_class
        if id:
            try:
                customer = get_object_or_404(Customer, pk=id)
                form = self.form_class(instance=customer)
            except Exception as err:
                return redirect("/home")

        return render(request, self.template_name, {"form": form})

    @method_decorator(login_required)
    def post(self, request,id=None):
        form = self.form_class
        user = request.user
        if id:
            try:
                customer = get_object_or_404(Customer, pk=id)
                form = CustomerForm(request.POST, instance=customer)
            except Exception as err:
                return redirect("/home")
        else :
            form = CustomerForm(request.POST)
        
        if form.is_valid():
            
            if id:
                self.customerService.update(customer)
            else :
                customer = form.save(commit=False)
                self.customerService.create(customer, user.id)
            return redirect("/home")

        return render(request, self.template_name, {"form": form})


class CustomerListView(SingleTableView):
    model = Customer
    table_class = CustomerTable
    template_name = 'main/home.html'
    redirect_url = "/home"
    paginator_class = LazyPaginator
    customerService = CustomerService()

    def get_context_data(self, **kwargs):
        queryset = kwargs.pop('object_list', None)
        if queryset is None:
            self.object_list = self.model.objects.all()
        return super().get_context_data(**kwargs)

    @method_decorator(login_required)
    def post(self, request, *args, **kwargs):
        customer_id = request.POST.get("customer-id")
        if customer_id:
            try:
                self.customerService.delete(customer_id)
            except Exception as err:
                return redirect(self.redirect_url)
        context = self.get_context_data(**kwargs)
        return render(request, self.template_name, context)

    @method_decorator(login_required)
    def get(self, request, *args, **kwargs):
        if (request.GET.get('sync_customer')):
            try:
                user = self.request.user
                self.customerService.sync_customer(user.id)
            except Exception as err:
                return redirect(self.redirect_url)
        context = self.get_context_data(**kwargs)
        return render(request, self.template_name, context)



class CustomerViewSet(viewsets.ModelViewSet):
    """
    API endpoint that allows Customer to be viewed or edited.
    """
    queryset = Customer.objects.all().order_by('-created_at')
    serializer_class = CustomerSerializer
    permission_classes = [permissions.IsAuthenticated]
    filter_backends = [DjangoFilterBackend]
    filterset_fields = ['nationality']

main/templates/main/actions_column.html
<div class="d-flex">
{% if user.is_staff or user == record.creator and perms.main.delete_customer %}
<form  method="post">
    {% csrf_token %}
    <button
      type="submit"
      class="btn btn-sm btn-danger"
      name="customer-id"
      value="{{ record.id }}"  >
      Delete
    </button>
  </form>
{% endif %}
{% if user.is_staff or user == record.creator and perms.main.change_customer %}
  <a class="btn btn-sm btn-warning ms-2" href="/customer/{{ record.id }}/update">Edit</a>
{% endif %}

</div>

main/templates/main/create_customer.html
{% extends 'layouts/base.html' %} {% block title %}Create a Customer{% endblock %} 
{% load crispy_forms_tags %}
{% block content %}
<form method="post">
  {% csrf_token %} {{form|crispy}}
  <button type="submit" class="btn btn-success">Post</button>
</form>
{% endblock %}

main/templates/main/customer_form.html
{% extends 'layouts/base.html' %} {% block title %}Create a Customer{% endblock %} 
{% load crispy_forms_tags %}
{% block content %}
<div class="container p-5">
  <h2 class="font-weight-bold mt-3">Customer</h2>
  <hr>
  <form method="post">
    {% csrf_token %} {{form|crispy}}
    <button type="submit" class="btn btn-success">Post</button>
  </form>
</div>
{% endblock %}

main/templates/main/home.html
{% extends 'layouts/base.html' %} {% block title %}Home Page{% endblock %}
{% load render_table from django_tables2 %}
{% block content %}
<div class="d-flex justify-content-end">
    <a class="btn btn-sm btn-warning m-2" href="/?sync_customer=true">Sync Customer</a>
    <a class="btn btn-sm btn-info m-2" href="/create-customer">Create Customer</a>    
</div>

{% render_table table %}

{% endblock %}